annotator_model: gpt-4o-mini-2024-07-18
tasks:
  - task_name: AIME24
    batch_size: 32
  - task_name: AMC23
    batch_size: 32
  - task_name: MATH500
    batch_size: 8
  - task_name: GPQADiamond
    batch_size: 8
  - task_name: BigCodeBench
    batch_size: 32
  - task_name: HumanEval
    batch_size: 32
  - task_name: MBPP
    batch_size: 16
  - task_name: LiveBench
    batch_size: 8
  - task_name: LiveCodeBench
    batch_size: 8